power <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
power2 <- power[power$Date %in% c("1/2/2007", "2/2/2007"),]
fdate <- as.POSIXct(strptime(paste(power2$Date, power2$Time), format = "%d/%m/%Y %H:%M:%S"))
a <- as.numeric(as.character(power2$Sub_metering_1))
png(filename="plot3.png", width=480, height=480,bg="transparent")
plot(fdate, a, col="black",type="l", xlab="", ylab = "Energy sub metering")
lines(fdate, as.numeric(as.character(power2$Sub_metering_2)), type="l", col="red")
lines(fdate, as.numeric(as.character(power2$Sub_metering_3)), type="l", col="blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()